// async function fun() {
//     // throw("404 Error")
//         return "hello";
// }

// fun()
// .then((result) =>{
//     console.log("success fully"); 
//     console.log(result);
    
// })
// .catch((error) =>{
//     console.log("error");
//     console.log(error);
    
// })


// Await 


a

